version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
    # Since ES 8, SSL is on by default, disabling on local
      - xpack.security.enabled=false
  api:
    container_name: api
    image: elastic-api-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    restart: always

volumes:
  elasticsearch: